global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:

  - job_name: 'mcio-demos-store-otel-collector'
    static_configs:
    - targets: ['mcio-demos-store-otel-collector:8889']
    - targets: ['mcio-demos-store-otel-collector:8888']

  - job_name: 'mcio-demos-store-prometheus'
    static_configs:
      - targets: ["mcio-demos-store-prometheus:9090"]
  
  - job_name: 'mcio-demos-store-postgres-exporter'
    static_configs:
      - targets: ["mcio-demos-store-postgres-exporter:9187"]
  
  - job_name: 'mcio-demos-store-redis-exporter'
    static_configs:
      - targets: ["mcio-demos-store-redis-exporter:9121"]
  
  - job_name: 'mcio-demos-store-mongo-exporter'
    static_configs:
      - targets: ['mcio-demos-store-mongo-exporter:9216']
  
  - job_name: 'mcio-demos-store-rabbitmq'
    static_configs:
      - targets: ['mcio-demos-store-rabbitmq:15692']
    metrics_path: /metrics
    params:
      vhost: ['/']
  
  - job_name: 'mcio-demos-store-zipkin'
    scrape_interval: 5s
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['mcio-demos-store-zipkin:9411']
  
  - job_name: 'mcio-demos-store-kafka-exporter'
    static_configs:
    - targets: ['mcio-demos-store-kafka-exporter:9308']