{
 "title": "ASP.NET Core Apps",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(process_runtime_dotnet_gc_collections_count_total,job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(process_runtime_dotnet_gc_collections_count_total{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "exported_job",
    "label": "exported_job",
    "query": {
     "query": "label_values(process_runtime_dotnet_gc_collections_count_total{job=~\"$job\"},exported_job)"
    }
   },
   {
    "name": "exported_instance",
    "query": {
     "query": "label_values(process_runtime_dotnet_gc_collections_count_total{exported_job~=\"$exported_job\"},exported_instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "GC - Garbage Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GC Collection Count",
   "type": "timeseries",
   "description": "Number of garbage collections that have occurred since process start.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "idelta(process_runtime_dotnet_gc_collections_count_total{job=\"$job\", instance=\"$instance\", exported_job=\"$exported_job\", exported_instance=~\"$exported_instance\"}[5m])"
    }
   ]
  },
  {
   "title": "GC Commited Memory Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(process_runtime_dotnet_gc_committed_memory_size_bytes{job=\"$job\", instance=\"$instance\", exported_job=\"$exported_job\", exported_instance=~\"$exported_instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "GC Heap Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(process_runtime_dotnet_gc_heap_size_bytes{job=\"$job\", instance=\"$instance\", exported_job=\"$exported_job\", exported_instance=~\"$exported_instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "GC Heap Fragmentation",
   "type": "timeseries",
   "description": "Number of garbage collections that have occurred since process start.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max_over_time(process_runtime_dotnet_gc_heap_fragmentation_size_bytes{job=\"$job\", instance=\"$instance\", exported_job=\"$exported_job\", exported_instance=~\"$exported_instance\"}[5m])"
    }
   ]
  }
 ]
}